name: Deploy to Firebase App Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAFESIGN_5DD44 }}'

      - name: Preview deploy to Firebase App Hosting
        run: npx firebase hosting:channel:deploy pr-${{ github.event.pull_request.number }} --project safesign-5dd44
