name: Deploy to Firebase App Hosting on merge

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAFESIGN_5DD44 }}'

      - name: Deploy to Firebase App Hosting
        run: npx firebase deploy --only apphosting --project safesign-5dd44
