name: Deploy to Cloud Run & Firebase Hosting

on:
  push:
    branches:
      - production  # ✅ 자동 배포 기준 브랜치

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ocr-safesign \
            --source . \
            --region asia-east1 \
            --allow-unauthenticated

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SA_KEY }}'
          channelId: live
          projectId: ${{ secrets.GCP_PROJECT }}
